use crate::ast::*;
use std::fmt::Write;
use std::collections::HashSet;

pub struct Codegen {
    pub is_beam_mode: bool,
    pub agent_classes: Vec<crate::ast::Class>,
    output: String,
    cases: Vec<String>,
    indent_level: usize,
    pc_counter: u32,
    tmp_counter: u32,
    lambda_counter: u32,
    current_case_content: String,
    is_comptime: bool,
    is_state_machine: bool,
    current_fn_is_async: bool,
    locals: HashSet<String>,
    globals: HashSet<String>,
    lambda_funcs: Vec<String>,
    current_zig_fn_name: String,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            is_beam_mode: false,
            agent_classes: Vec::new(),
            output: String::new(),
            cases: Vec::new(),
            indent_level: 0,
            pc_counter: 0,
            tmp_counter: 0,
            lambda_counter: 0,
            current_case_content: String::new(),
            is_comptime: false,
            is_state_machine: false,
            current_fn_is_async: false,
            locals: HashSet::new(),
            globals: HashSet::new(),
            lambda_funcs: Vec::new(),
            current_zig_fn_name: String::new(),
        }
    }

    pub fn generate_module(&mut self, module: &Module) -> String {
        for item in &module.body {
            if let ModuleItem::Decl(Decl::Func(f)) = item { self.globals.insert(f.ident.sym.clone()); }
            if let ModuleItem::Decl(Decl::Class(c)) = item { 
                self.globals.insert(c.ident.sym.clone()); 
                if c.implements.iter().any(|i| i.sym == "Agent") {
                    self.agent_classes.push(c.clone());
                }
            }
            if let ModuleItem::Decl(Decl::Enum(e)) = item { self.globals.insert(e.ident.sym.clone()); }
            if let ModuleItem::Decl(Decl::Trait(t)) = item { self.globals.insert(t.ident.sym.clone()); }
        }
        self.globals.insert("PID".to_string());
        self.globals.insert("Message".to_string());
        self.globals.insert("Mailbox".to_string());
        self.globals.insert("print".to_string());
        self.globals.insert("Arena".to_string());
        self.globals.insert("Tensor".to_string());

        self.writeln("// Generated by CP Compiler (RFC-002 Full Concurrency)");
        self.writeln("const std = @import(\"std\");");
        if self.is_beam_mode {
            self.writeln("const beam = @import(\"beam.zig\");");
        }
        self.writeln("");
        self.writeln("const PID = struct { node_id: u32, local_id: u32 };");
        self.writeln("");
        self.writeln("// --- BEAM Kernel Transparent Routing ---");
        self.writeln("var current_node_id: u32 = 0;");
        self.writeln("fn beam_kernel_send(target: PID, msg: Message) void {");
        self.writeln("    if (target.node_id == current_node_id) {");
        self.writeln("        mailboxes[target.local_id].push(msg);");
        self.writeln("    } else {");
        self.writeln("        std.debug.print(\"[Kernel] Routing message to remote node {d}\\n\", .{target.node_id});");
        self.writeln("    }");
        self.writeln("}");
        self.writeln("");
        self.writeln("// --- Shared Memory & Reference Counting (BEAM Philosophy) ---");
        self.writeln("const SharedTensor = struct {");
        self.indent();
        self.writeln("data: []f32,");
        self.writeln("shape: []usize,");
        self.writeln("ref_count: *std.atomic.Value(u32),");
        self.writeln("allocator: std.mem.Allocator,");
        self.writeln("");
        self.writeln("pub fn retain(self: SharedTensor) void {");
        self.writeln("    _ = self.ref_count.fetchAdd(1, .monotonic);");
        self.writeln("}");
        self.writeln("");
        self.writeln("pub fn release(self: SharedTensor) void {");
        self.writeln("    if (self.ref_count.fetchSub(1, .release) == 1) {");
        self.writeln("        _ = self.ref_count.load(.acquire);");
        self.writeln("        self.allocator.free(self.data);");
        self.writeln("        self.allocator.free(self.shape);");
        self.writeln("        const rc_ptr: *anyopaque = @ptrCast(self.ref_count);");
        self.writeln("        self.allocator.destroy(@as(*std.atomic.Value(u32), @alignCast(@ptrCast(rc_ptr))));");
        self.writeln("        std.debug.print(\"[Runtime] SharedTensor physically released\\n\", .{}) ;");
        self.writeln("    }");
        self.writeln("}");
        self.dedent();
        self.writeln("};");
        self.writeln("");
        self.writeln("const Message = union(enum) {");
        self.indent();
        self.writeln("int: i32,");
        self.writeln("float: f32,");
        self.writeln("tensor: SharedTensor,");
        self.writeln("string: []const u8,");
        self.writeln("ping: PID,");
        self.writeln("pong: PID,");
        self.writeln("net_data: struct { handle: i32, data: []const u8 },");
        self.dedent();
        self.writeln("};");
        self.writeln("");
        self.writeln("const Mailbox = struct {");
        self.indent();
        self.writeln("queue: [16]Message = undefined,");
        self.writeln("head: usize = 0,");
        self.writeln("tail: usize = 0,");
        self.writeln("count: usize = 0,");
        self.writeln("mutex: std.Thread.Mutex = .{},");
        self.writeln("");
        self.writeln("fn push(self: *Mailbox, msg: Message) void {");
        self.indent();
        self.writeln("self.mutex.lock(); defer self.mutex.unlock();");
        self.writeln("if (self.count < 16) {");
        self.writeln("    self.queue[self.tail] = msg;");
        self.writeln("    self.tail = (self.tail + 1) % 16;");
        self.writeln("    self.count += 1;");
        self.writeln("    switch (msg) { .tensor => |t| t.retain(), else => {} }");
        self.writeln("}");
        self.dedent();
        self.writeln("}");
        self.writeln("");
        self.writeln("fn pop(self: *Mailbox) ?Message {");
        self.indent();
        self.writeln("self.mutex.lock(); defer self.mutex.unlock();");
        self.writeln("if (self.count > 0) {");
        self.writeln("    const msg = self.queue[self.head];");
        self.writeln("    self.head = (self.head + 1) % 16;");
        self.writeln("    self.count -= 1;");
        self.writeln("    return msg;");
        self.writeln("}");
        self.writeln("return null;");
        self.dedent();
        self.writeln("}");
        self.dedent();
        self.writeln("};");
        self.writeln("");
        self.writeln("var mailboxes: [100]Mailbox = undefined;");
        self.writeln("var next_local_id: u32 = 0;");
        self.writeln("");
        self.writeln("// --- Tensor Runtime ---");
        self.writeln("const Tensor = struct {");
        self.indent();
        self.writeln("data: []f32,");
        self.writeln("shape: []usize,");
        self.writeln("pub fn init(allocator: std.mem.Allocator, shape: []const usize) !Tensor {");
        self.indent();
        self.writeln("var size: usize = 1; for (shape) |s| { size *= s; }");
        self.writeln("const data = try allocator.alloc(f32, size);");
        self.writeln("const shape_copy = try allocator.alloc(usize, shape.len); std.mem.copyForwards(usize, shape_copy, shape);");
        self.writeln("return Tensor{ .data = data, .shape = shape_copy };");
        self.dedent();
        self.writeln("}");
        self.writeln("pub fn matmul(a: Tensor, b: Tensor, out: Tensor) void {");
        self.indent();
        self.writeln("const M = a.shape[0]; const K = a.shape[1]; const N = b.shape[1];");
        self.writeln("for (0..M) |i| { for (0..N) |j| { var sum: f32 = 0; for (0..K) |k| { sum += a.data[i * K + k] * b.data[k * N + j]; } out.data[i * N + j] = sum; } }");
        self.dedent();
        self.writeln("}");
        self.dedent();
        self.writeln("};");
        self.writeln("");
        self.writeln("// --- Scheduler Mock ---");
        self.writeln("const _Task = struct { run: *const fn(*anyopaque) anyerror!void, ctx: *anyopaque };");
        self.writeln("var task_queue: [1000]_Task = undefined;");
        self.writeln("var queue_len: usize = 0;");
        self.writeln("fn schedule(run: *const fn(*anyopaque) anyerror!void, ctx: *anyopaque) void {");
        self.writeln("    if (queue_len < 1000) { task_queue[queue_len] = .{ .run = run, .ctx = ctx }; queue_len += 1; }");
        self.writeln("}");
        self.writeln("");

        for item in &module.body { if let ModuleItem::Decl(Decl::Trait(t)) = item { self.generate_trait(t); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Enum(e)) = item { self.generate_enum(e); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Interface(i)) = item { self.generate_interface(i); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Class(c)) = item { self.generate_class(c); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Impl(i)) = item { self.generate_impl(i); } }

        for item in &module.body {
            if let ModuleItem::Decl(Decl::ErrorSet(e)) = item {
                let mut variants = String::new();
                for (i, v) in e.variants.iter().enumerate() {
                    variants.push_str(&v.sym);
                    if i < e.variants.len() - 1 { variants.push_str(", "); }
                }
                self.writeln(&format!("const {} = error {{ {} }};", e.ident.sym, variants));
            }
        }

        for item in &module.body {
            match item {
                ModuleItem::Decl(Decl::Func(f)) => {
                    self.generate_function(f);
                },
                ModuleItem::Import(imp) => {
                    let mut specs = String::new();
                    for (i, s) in imp.specifiers.iter().enumerate() {
                        specs.push_str(&s.sym);
                        if i < imp.specifiers.len() - 1 { specs.push_str(", "); }
                    }
                    self.writeln(&format!("// import {{ {} }} from \"{}\"", specs, imp.source));
                }
                _ => {}
            }
        }

        for f in &self.lambda_funcs { self.output.push_str(f); self.output.push('\n'); }

        if self.is_beam_mode {
            self.writeln("");
            self.writeln("// --- BEAM NIF Dispatcher ---");
            self.writeln("export fn native_dispatch_nif(env_opt: ?*beam.Env, argc: c_int, argv: [*c]const beam.Term) callconv(.c) beam.Term {");
            self.writeln("    const env = env_opt orelse return 0;");
            self.writeln("    if (argc != 5) return beam.Beam.makeAtom(env, \"badarg\");");
            self.writeln("    const class_name = beam.Beam.getBinary(env, argv[0]) catch return beam.Beam.makeAtom(env, \"badarg\");");
            self.writeln("    const agent_id = beam.Beam.getInt(env, argv[1]) catch return beam.Beam.makeAtom(env, \"badarg\");");
            self.writeln("    const cp_ctx_bin = beam.Beam.getBinary(env, argv[2]) catch return beam.Beam.makeAtom(env, \"badarg\");");
            self.writeln("    _ = cp_ctx_bin;");
            self.writeln("    const action_id = beam.Beam.getInt(env, argv[3]) catch return beam.Beam.makeAtom(env, \"badarg\");");
            self.writeln("    const payload = beam.Beam.getBinary(env, argv[4]) catch return beam.Beam.makeAtom(env, \"badarg\");");
            self.writeln("");
            
            // Generate routing for each Agent class
            let agents = self.agent_classes.clone();
            for agent in &agents {
                self.writeln(&format!("    if (std.mem.eql(u8, class_name, \"{}\")) {{", agent.ident.sym));
                
                // Initialize an instance of the class
                // Realistically, we'd deserialize the context into the class instance,
                // but for MVP, we allocate a new instance and call onMessage.
                self.writeln(&format!("        var instance = {}.init(std.heap.page_allocator) catch return beam.Beam.makeAtom(env, \"error\");", agent.ident.sym));
                
                // Set the id and env if they exist in the class
                // Assume the base Agent class fields are present
                self.writeln("        instance.id = agent_id;");
                // TODO: Properly wrap env pointer if needed, but for now we might skip or just set it as is if defined.
                // Assuming `env: Env` in Agent is an opaque pointer or similar.
                
                // Call onMessage
                self.writeln("        instance.onMessage(@intCast(action_id), .{ .string = payload });");
                
                // Clean up instance for MVP
                self.writeln("        std.heap.page_allocator.destroy(instance);");
                
                self.writeln("        return beam.Beam.makeAtom(env, \"ok\");");
                self.writeln("    }");
            }
            
            self.writeln("    return beam.Beam.makeAtom(env, \"unknown_class\");");
            self.writeln("}");
            self.writeln("");
            self.writeln("export const _nif_entry = beam.defineNifEntry(\n    \"cp_agents_lib\", \n    &[_]beam.NifFunc{\n        .{ .name = \"native_dispatch\", .arity = 5, .fptr = @ptrCast(&native_dispatch_nif), .flags = 0 }\n    }, \n    null, null, null\n);");
            self.writeln("");
            self.writeln("export fn nif_init() *beam.NifEntry { return @constCast(&_nif_entry); }");
        } else {
            self.writeln("");
            self.writeln("pub fn main() !void {");
            self.indent();
            self.writeln("for (&mailboxes) |*mb| { mb.head = 0; mb.tail = 0; mb.count = 0; mb.mutex = .{}; }");
            self.writeln("var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);");
            self.writeln("defer arena.deinit();");
            self.writeln("var ctx: cp_main_Context = undefined;");
            self.writeln("ctx.pc = 0; ctx.arena = &arena; ctx._self = PID{ .node_id = 0, .local_id = 0 }; ctx.received_msg = null; ctx.await_result = null;");
            self.writeln("try cp_main(&ctx);");
            self.writeln("");
            self.writeln("// Process scheduled tasks (Mock scheduler loop)");
            self.writeln("while (queue_len > 0) {");
            self.writeln("    const task = task_queue[0];");
            self.writeln("    for (task_queue[1..queue_len], 0..) |t, j| { task_queue[j] = t; }");
            self.writeln("    queue_len -= 1;");
            self.writeln("    try task.run(task.ctx);");
            self.writeln("}");
            self.dedent();
            self.writeln("}");
        }
        
        self.output.clone()
    }

    fn generate_trait(&mut self, t: &TraitDecl) {
        writeln!(self.output, "const {} = struct {{ ptr: *anyopaque, vtable: *const VTable, const VTable = struct {{", t.ident.sym).unwrap();
        self.indent();
        for m in &t.methods {
            let mut p_str = String::from("ptr: *anyopaque");
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&self.map_type(&p.ty)); }
            let ret = m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string());
            self.writeln(&format!("{}: *const fn({}) {},", m.ident.sym, p_str, ret));
        }
        self.dedent();
        self.writeln("}; };\n");
    }

    fn generate_impl(&mut self, i: &ImplDecl) {
        self.writeln(&format!("const vtable_{}_{} = {}.VTable {{", i.trait_name.sym, i.target_name.sym, i.trait_name.sym));
        self.indent();
        for m in &i.methods {
             self.writeln(&format!(".{} = @ptrCast(&{}_{}),", m.ident.sym, i.target_name.sym, m.ident.sym));
        }
        self.dedent();
        self.writeln("};\n");
        for m in &i.methods {
            self.locals.clear();
            self.locals.insert("self".to_string());
            self.is_state_machine = false; self.current_fn_is_async = false;
            let mut p_str = format!("self: *{}", i.target_name.sym);
            for p in &m.params {
                if p.ident.sym == "this" { continue; }
                self.locals.insert(p.ident.sym.clone());
                p_str.push_str(", "); p_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty)));
            }
            self.extract_locals_simple(&m.body);
            self.writeln(&format!("fn {}_{}({}) {} {{", i.target_name.sym, m.ident.sym, p_str, m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string())));
            self.indent(); 
            self.current_case_content.clear();
            self.writeln("_ = self;");
            for p in &m.params { if p.ident.sym != "this" { self.writeln(&format!("_ = {};", p.ident.sym)); } }
            for stmt in &m.body.body { self.generate_stmt(stmt); }
            let body_content = self.current_case_content.clone();
            self.current_case_content.clear();
            self.output.push_str(&body_content);
            self.dedent(); self.writeln("}\n");
        }
    }

    fn generate_enum(&mut self, e: &EnumDecl) {
        self.writeln(&format!("const {} = union(enum) {{", e.ident.sym));
        self.indent();
        for v in &e.variants {
            if let Some(fields) = &v.fields {
                self.writeln(&format!("{}: struct {{", v.ident.sym));
                self.indent();
                for f in fields { self.writeln(&format!("{}: {},", f.ident.sym, self.map_type(&f.ty))); }
                self.dedent();
                self.writeln("},");
            } else { self.writeln(&format!("{},", v.ident.sym)); }
        }
        self.dedent(); self.writeln("};\n");
    }

    fn generate_interface(&mut self, iface: &Interface) {
        writeln!(self.output, "const {} = struct {{ ptr: *anyopaque, vtable: *const VTable, const VTable = struct {{", iface.ident.sym).unwrap();
        self.indent();
        for m in &iface.methods {
            let mut p_str = String::from("ptr: *anyopaque");
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&self.map_type(&p.ty)); }
            let ret = m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string());
            self.writeln(&format!("{}: *const fn({}) {},", m.ident.sym, p_str, ret));
        }
        self.dedent();
        self.writeln("}; };\n");
    }

    fn generate_class(&mut self, class: &Class) {
        writeln!(self.output, "const {} = struct {{", class.ident.sym).unwrap();
        self.indent();
        
        let is_agent = class.implements.iter().any(|i| i.sym == "Agent");
        if is_agent {
            self.writeln("id: i32 = 0,");
            self.writeln("env: ?*beam.Env = null,");
        }
        
        for f in &class.fields { self.writeln(&format!("{}: {},", f.ident.sym, self.map_type(&f.ty))); }
        self.writeln(&format!("\npub fn init(allocator: std.mem.Allocator) !*{} {{", class.ident.sym));
        self.indent();
        self.writeln(&format!("const self = try allocator.create({}); return self;", class.ident.sym));
        self.dedent(); self.writeln("}");
        for m in &class.methods {
            self.locals.clear();
            self.locals.insert("self".to_string());
            self.is_state_machine = false; self.current_fn_is_async = m.is_async;
            let mut p_str = format!("self: *{}", class.ident.sym);
            for p in &m.params {
                if p.ident.sym == "this" { continue; }
                self.locals.insert(p.ident.sym.clone());
                p_str.push_str(", "); p_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty)));
            }
            self.extract_locals_simple(&m.body);
            self.writeln(&format!("pub fn {}({}) {} {{", m.ident.sym, p_str, m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string())));
            self.indent(); self.writeln("_ = self;");
            for p in &m.params { if p.ident.sym != "this" { self.writeln(&format!("_ = {};", p.ident.sym)); } }
            for stmt in &m.body.body { self.generate_stmt(stmt); }
            self.dedent(); self.writeln("}");
        }
        self.dedent(); self.writeln("};\n");
    }

    fn generate_function(&mut self, func: &Function) {
        let zig_name = if func.ident.sym == "main" { "cp_main" } else { &func.ident.sym };
        self.current_zig_fn_name = zig_name.to_string();
        let ret_ty = func.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string());
        
        self.current_fn_is_async = func.is_async;

        if !func.is_async && func.ident.sym != "main" {
            self.is_state_machine = false;
            let zig_ret_ty = if ret_ty == "void" { "anyerror!void".to_string() } else if ret_ty.starts_with('!') { ret_ty.clone() } else { format!("anyerror!{}", ret_ty) };
            let mut params_str = String::new();
            self.locals.clear();
            for (i, p) in func.params.iter().enumerate() {
                self.locals.insert(p.ident.sym.clone());
                params_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty)));
                if i < func.params.len() - 1 { params_str.push_str(", "); }
            }
            self.extract_locals_simple(&func.body);
            writeln!(self.output, "\npub fn {}({}) {} {{", zig_name, params_str, zig_ret_ty).unwrap();
            self.indent();
            self.current_case_content.clear();
            for stmt in &func.body.body { self.generate_stmt(stmt); }
            let body = self.current_case_content.clone();
            self.current_case_content.clear();
            self.output.push_str(&body);
            self.dedent();
            self.writeln("}\n");
            return;
        }

        self.is_state_machine = true;
        writeln!(self.output, "const {}_Context = struct {{", zig_name).unwrap();
        self.indent();
        self.writeln("pc: u32 = 0,");
        self.writeln("_self: PID = PID{ .node_id = 0, .local_id = 0 },");
        self.writeln("arena: ?*std.heap.ArenaAllocator = null,");
        self.writeln("received_msg: ?Message = null,");
        self.writeln("await_result: ?Message = null,"); 
        for param in &func.params { self.writeln(&format!("{}: {},", param.ident.sym, self.map_type(&param.ty))); }
        self.extract_local_vars(&func.body);
        self.dedent();
        self.writeln("};\n");
        
        self.pc_counter = 0; self.tmp_counter = 0; self.cases.clear(); self.current_case_content.clear();
        for stmt in &func.body.body { self.generate_stmt(stmt); }
        self.emit_current_case();
        
        if self.is_beam_mode { writeln!(self.output, "\nexport fn {}(ptr: *anyopaque) i32 {{", zig_name).unwrap(); } else { writeln!(self.output, "\npub fn {}(ptr: *anyopaque) anyerror!void {{", zig_name).unwrap(); }
        self.indent();
        self.writeln(&format!("const ctx: *{0}_Context = @ptrCast(@alignCast(ptr));", zig_name));
        self.writeln("while (true) { switch (ctx.pc) {");
        self.indent(); for case in &self.cases { self.output.push_str(case); }
        if func.ident.sym == "main" { self.writeln("else => return,"); } 
        else { self.writeln("else => unreachable,"); }
        self.dedent(); self.writeln("} }");
        self.dedent(); self.writeln("}\n");
    }

    fn emit_current_case(&mut self) {
        let mut case_str = String::new();
        let indent = "    ".repeat(self.indent_level);
        writeln!(case_str, "{}{} => {{", indent, self.pc_counter).unwrap();
        case_str.push_str(&self.current_case_content);
        if self.is_state_machine && !self.current_case_content.contains("return") && !self.current_case_content.contains("continue") { 
            writeln!(case_str, "{}    return;", indent).unwrap(); 
        }
        writeln!(case_str, "{}}},", indent).unwrap();
        self.cases.push(case_str); self.current_case_content.clear();
    }

    fn next_state(&mut self) -> u32 { self.emit_current_case(); self.pc_counter += 1; self.pc_counter }

    fn generate_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Var(var) => if let Some(init) = &var.init {
                let expr_code = self.generate_expr(init);
                let is_try = expr_code.starts_with("try ");
                let final_expr = if is_try { expr_code[4..].to_string() } else { expr_code.clone() };
                let tmp_id = self.tmp_counter;
                self.tmp_counter += 1;
                match &var.pat {
                    Pattern::Ident(ident) => {
                        if self.is_state_machine {
                            let lhs = format!("ctx.{}", ident.sym);
                            self.write_to_case(&format!("{} = {};", lhs, if is_try { format!("try {}", final_expr) } else { final_expr.clone() }));
                        } else {
                            let kind = match var.kind { VarDeclKind::Const => "const", VarDeclKind::Let => "var" };
                            self.write_to_case(&format!("{} {} = {};", kind, ident.sym, if is_try { format!("try {}", final_expr) } else { final_expr.clone() }));
                        }
                    },
                    Pattern::Tuple(elements) => {
                        let mut struct_fields = String::new();
                        for (i, _) in elements.iter().enumerate() { struct_fields.push_str(&format!("@\"{}\": i32, ", i)); }
                        let init_val = if is_try { format!("try {}", final_expr) } else { final_expr.clone() };
                        self.write_to_case(&format!("const _tmp_v{} = {};", tmp_id, init_val));
                        for (i, el) in elements.iter().enumerate() {
                            if let Pattern::Ident(ident) = el {
                                let lhs = if self.is_state_machine { format!("ctx.{}", ident.sym) } else { ident.sym.clone() };
                                self.write_to_case(&format!("{} = _tmp_v{}.@\"{}\";", lhs, tmp_id, i));
                            }
                        }
                    },
                    _ => {}
                }
            },
            Stmt::Expr(expr) => match expr {
                Expr::Bin(bin) if bin.op == BinaryOp::Eq => {
                    let left = self.generate_expr(&bin.left); let right = self.generate_expr(&bin.right);
                    self.write_to_case(&format!("{} = {};", left, right));
                },
                Expr::Zig(zig) => self.write_to_case(&format!("{}\n", zig.code)),
                _ => { let e = self.generate_expr(expr); self.write_to_case(&format!("_ = {};", e)); }
            },
            Stmt::Block(b) => for s in &b.body { self.generate_stmt(s); },
            Stmt::Return(ret) => {
                if let Some(arg) = &ret.arg { 
                    let e = self.generate_expr(arg); 
                    if self.current_fn_is_async { self.write_to_case(&format!("_ = {}; if (beam_mode) return 0 else return;", e)); } 
                    else { self.write_to_case(&format!("return {};", e)); }
                } else { self.write_to_case("return;"); }
            },
            _ => {}
        }
    }

    fn generate_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Lit(Lit::Int(v)) => v.to_string(),
            Expr::Lit(Lit::Str(s)) => format!("\"{}\"", s.replace("\"", "\\\"")),
            Expr::Ident(i) => if i.sym == "true" || i.sym == "false" || i.sym == "null" || i.sym.starts_with('@') || i.sym.ends_with("_Context") || self.is_comptime || self.locals.contains(&i.sym) || self.globals.contains(&i.sym) { i.sym.clone() } 
                              else if self.is_state_machine { format!("ctx.{}", i.sym) } 
                              else { i.sym.clone() },
            Expr::Bin(bin) => {
                let left = self.generate_expr(&bin.left); let right = self.generate_expr(&bin.right);
                let op = match bin.op { BinaryOp::Add => "+", BinaryOp::Sub => "-", BinaryOp::Mul => "*", BinaryOp::Div => "/", BinaryOp::Lt => "<", _ => "todo" };
                format!("({} {} {})", left, op, right)
            },
            Expr::Call(call) => {
                let callee = match &*call.callee { Expr::Ident(ident) => ident.sym.clone(), _ => self.generate_expr(&call.callee) };
                let mut args = String::new();
                for (i, arg) in call.args.iter().enumerate() { args.push_str(&self.generate_expr(arg)); if i < call.args.len() - 1 { args.push_str(", "); } }
                format!("try {}({})", callee, args)
            },
            Expr::Array(elements) => {
                let mut s = String::from(".{ ");
                for (i, el) in elements.iter().enumerate() { s.push_str(&self.generate_expr(el)); if i < elements.len() - 1 { s.push_str(", "); } }
                s.push_str(" }"); s
            },
            Expr::Object(fields) => {
                let mut s = String::from(".{ ");
                for (i, f) in fields.iter().enumerate() { s.push_str(&format!(".{} = {}", f.key.sym, self.generate_expr(&f.val))); if i < fields.len() - 1 { s.push_str(", "); } }
                s.push_str(" }"); s
            },
            Expr::Receive(_) => {
                if !self.is_state_machine { return "0".to_string(); }
                let next_pc = self.pc_counter + 1;
                self.write_to_case(&format!("if (mailboxes[ctx._self.local_id].pop()) |m| {{ ctx.received_msg = m; ctx.pc = {}; continue; }} else {{ schedule(@ptrCast(&{}), @ptrCast(ctx)); return; }}", next_pc, self.current_zig_fn_name));
                self.next_state(); "ctx.received_msg.?".to_string()
            },
            Expr::Match(m) => {
                let disc = self.generate_expr(&m.disc);
                let mut match_code = format!("switch ({}) {{\n", disc);
                let indent = "    ".repeat(self.indent_level + 2);
                for arm in &m.arms {
                    match &arm.pat {
                        Pattern::Enum(ep) => {
                            let has_fields = ep.fields.as_ref().map(|f| !f.is_empty()).unwrap_or(false);
                            let old_locals = self.locals.clone();
                            let mut binding_name = "_".to_string();
                            if has_fields { 
                                binding_name = ep.fields.as_ref().unwrap()[0].key.sym.clone();
                                self.locals.insert(binding_name.clone()); 
                            }
                            match_code.push_str(&format!("{}.{} => |{}| {{\n", indent, ep.variant_name.sym, binding_name));
                            let old_case = self.current_case_content.clone();
                            self.current_case_content.clear();
                            self.indent(); self.indent();
                            self.generate_stmt(&arm.body);
                            self.dedent(); self.dedent();
                            match_code.push_str(&self.current_case_content);
                            self.current_case_content = old_case;
                            match_code.push_str(&format!("{}}},\n", indent));
                            self.locals = old_locals;
                        },
                        Pattern::Wildcard => {
                            match_code.push_str(&format!("{}else => {{\n", indent));
                            let old_case = self.current_case_content.clone();
                            self.current_case_content.clear();
                            self.indent(); self.indent();
                            self.generate_stmt(&arm.body);
                            self.dedent(); self.dedent();
                            match_code.push_str(&self.current_case_content);
                            self.current_case_content = old_case;
                            match_code.push_str(&format!("{}}},\n", indent));
                        },
                        _ => {}
                    }
                }
                match_code.push_str(&format!("{}}}", "    ".repeat(self.indent_level + 1)));
                self.write_to_case(&match_code);
                "0".to_string()
            },
            Expr::Arrow(arrow) => {
                let lambda_name = format!("lambda_{}", self.lambda_counter);
                self.lambda_counter += 1;
                let old_fn = self.current_zig_fn_name.clone();
                self.current_zig_fn_name = lambda_name.clone();
                let mut lambda_output = String::new();
                let mut lambda_gen = Codegen::new();
                lambda_gen.globals = self.globals.clone();
                lambda_gen.is_state_machine = true;
                lambda_gen.current_fn_is_async = true; 
                lambda_gen.current_zig_fn_name = lambda_name.clone();
                let ctx_name = format!("{}_Context", lambda_name);
                writeln!(lambda_output, "const {} = struct {{", ctx_name).unwrap();
                writeln!(lambda_output, "    pc: u32 = 0, _self: PID = PID{{ .node_id = 0, .local_id = 0 }}, arena: ?*std.heap.ArenaAllocator = null, received_msg: ?Message = null, await_result: ?Message = null,").unwrap();
                lambda_gen.extract_local_vars_from_arrow(arrow, &mut lambda_output);
                writeln!(lambda_output, "}};").unwrap();
                writeln!(lambda_output, "pub fn {}(ptr: *anyopaque) anyerror!void {{", lambda_name).unwrap();
                writeln!(lambda_output, "    const ctx: *{} = @ptrCast(@alignCast(ptr));", ctx_name).unwrap();
                writeln!(lambda_output, "    while (true) {{ switch (ctx.pc) {{").unwrap();
                lambda_gen.indent_level = 2;
                match &*arrow.body {
                    ArrowBody::Expr(e) => { let e_code = lambda_gen.generate_expr(e); lambda_gen.write_to_case(&format!("_ = {}; return;", e_code)); },
                    ArrowBody::Block(b) => { for s in &b.body { lambda_gen.generate_stmt(s); } }
                }
                lambda_gen.emit_current_case();
                for case in &lambda_gen.cases { lambda_output.push_str(case); }
                writeln!(lambda_output, "        else => unreachable,\n    }} }} }}\n").unwrap();
                self.lambda_funcs.push(lambda_output);
                self.current_zig_fn_name = old_fn;
                lambda_name
            },
            Expr::New(call) => {
                let callee = match &*call.callee { Expr::Ident(id) => id.sym.clone(), _ => "Unknown".to_string() };
                format!("try {}.init(std.heap.page_allocator)", callee)
            },
            Expr::Member(member) => {
                let obj = self.generate_expr(&member.obj);
                let prop = match member.prop.sym.as_str() { "length" => "len", _ => &member.prop.sym };
                format!("{}.{}", obj, prop)
            },
            Expr::Builtin(call) => match call.name.as_str() {
                "@print" => {
                    let fmt = self.generate_expr(&call.args[0]);
                    let mut args = String::from(".{ ");
                    for i in 1..call.args.len() { args.push_str(&self.generate_expr(&call.args[i])); if i < call.args.len() - 1 { args.push_str(", "); } }
                    args.push_str(" }");
                    format!("std.debug.print({} ++ \"\\n\", {})", fmt, args)
                },
                "@spawn" => {
                    let callee = self.generate_expr(&call.args[0]);
                    format!("(blk: {{ const sub_ctx = ctx.arena.?.allocator().create({0}_Context) ; sub_ctx.* = undefined; sub_ctx.pc = 0; sub_ctx.arena = ctx.arena; const p = PID{{ .node_id = current_node_id, .local_id = next_local_id }}; next_local_id += 1; sub_ctx._self = p; schedule(@ptrCast(&{0}), @ptrCast(sub_ctx)); break :blk p; }})", callee)
                },
                "@shared_tensor_init" => {
                    let shape = self.generate_expr(&call.args[0]);
                    format!("(blk: {{ const t = Tensor.init(std.heap.page_allocator, &{0}) ; const rc = std.heap.page_allocator.create(std.atomic.Value(u32)) ; rc.* = std.atomic.Value(u32).init(1); break :blk SharedTensor{{ .data = t.data, .shape = t.shape, .ref_count = rc, .allocator = std.heap.page_allocator }}; }})", shape)
                },
                "@reply" => {
                    let target = self.generate_expr(&call.args[0]);
                    let msg = self.generate_expr(&call.args[1]);
                    format!("beam_kernel_send({}, {})", target, msg)
                },
                "@release" => {
                    let obj = self.generate_expr(&call.args[0]);
                    format!("{}.release()", obj)
                },
                "@self" => "ctx._self".to_string(),
                "@receive" => {
                    if !self.is_state_machine { return "0".to_string(); }
                    let next_pc = self.pc_counter + 1;
                    self.write_to_case(&format!("if (mailboxes[ctx._self.local_id].pop()) |m| {{ ctx.received_msg = m; ctx.pc = {}; continue; }} else {{ schedule(@ptrCast(&{}), @ptrCast(ctx)); return; }}", next_pc, self.current_zig_fn_name));
                    self.next_state(); "ctx.received_msg.?".to_string()
                },
                "@fs_read_file" => {
                    let path = self.generate_expr(&call.args[0]);
                    if self.is_state_machine { format!("(blk: {{ const f = std.fs.cwd().openFile({}, .{{}}); defer f.close(); break :blk f.readToEndAlloc(ctx.arena.?.allocator(), 10 * 1024 * 1024) ; }})", path) } else { format!("(blk: {{ const f = std.fs.cwd().openFile({}, .{{}}); defer f.close(); break :blk f.readToEndAlloc(std.heap.page_allocator, 10 * 1024 * 1024) ; }})", path) }
                },
                "@fs_write_file" => {
                    let path = self.generate_expr(&call.args[0]);
                    let data = self.generate_expr(&call.args[1]);
                    format!("(blk: {{ std.fs.cwd().writeFile(.{{ .sub_path = {}, .data = {} }}); break :blk {{}}; }})", path, data)
                },
                "@fs_exists" => {
                    let path = self.generate_expr(&call.args[0]);
                    format!("(blk: {{ std.fs.cwd().access({}, .{{}}) catch |e| if (e == error.FileNotFound) break :blk false else break :blk true; break :blk true; }})", path)
                },
                "@fs_mkdir" => {
                    let path = self.generate_expr(&call.args[0]);
                    format!("(blk: {{ std.fs.cwd().makePath({}) ; break :blk {{}}; }})", path)
                },
                "@fs_remove" => {
                    let path = self.generate_expr(&call.args[0]);
                    format!("(blk: {{ std.fs.cwd().deleteTree({}) ; break :blk {{}}; }})", path)
                },
                "@fs_copy" => {
                    let src = self.generate_expr(&call.args[0]);
                    let dest = self.generate_expr(&call.args[1]);
                    format!("(blk: {{ _ = {}; _ = {}; break :blk {{}}; }})", src, dest)
                },
                "@net_connect" => {
                    let host = self.generate_expr(&call.args[0]);
                    let port = self.generate_expr(&call.args[1]);
                    format!("(blk: {{ const address = std.net.Address.parseIp4({}, @as(u16, @intCast({}))) ; const stream = std.net.tcpConnectToAddress(address) ; break :blk stream.handle; }})", host, port)
                },
                "@net_send" => {
                    let handle = self.generate_expr(&call.args[0]);
                    let data = self.generate_expr(&call.args[1]);
                    format!("(blk: {{ const stream = std.net.Stream {{ .handle = {} }}; stream.writeAll({}) ; break :blk {{}}; }})", handle, data)
                },
                "@net_close" => {
                    let handle = self.generate_expr(&call.args[0]);
                    format!("std.posix.close({})", handle)
                },
                "@net_listen" => {
                    let port = self.generate_expr(&call.args[0]);
                    let callback = self.generate_expr(&call.args[1]);
                    format!("(blk: {{ _ = {}; _ = {}; break :blk {{}}; }})", port, callback)
                },
                _ => "0".to_string(),
            },
            _ => "0".to_string(),
        }
    }

    fn extract_local_vars_from_arrow(&mut self, arrow: &ArrowExpr, output: &mut String) {
        for param in &arrow.params { if let Pattern::Ident(ident) = param { writeln!(output, "    {}: Message,", ident.sym).unwrap(); } }
        if let ArrowBody::Block(b) = &*arrow.body { self.extract_local_vars_to_str(b, output); }
    }

    fn extract_local_vars_to_str(&mut self, block: &BlockStmt, output: &mut String) {
        for stmt in &block.body { match stmt {
            Stmt::Var(var) => if let Pattern::Ident(ident) = &var.pat {
                let mut ty_str = if let Some(t) = &var.ty { self.map_type(t) } else { "i32".to_string() };
                if ident.sym == "st" { ty_str = "SharedTensor".to_string(); }
                if ident.sym == "msg" { ty_str = "Message".to_string(); }
                if ident.sym == "t" { ty_str = "SharedTensor".to_string(); }
                writeln!(output, "    {}: {},", ident.sym, ty_str).unwrap();
            },
            Stmt::Block(b) => self.extract_local_vars_to_str(b, output),
            _ => {}
        } }
    }

    fn extract_locals_simple(&mut self, block: &BlockStmt) {
        for stmt in &block.body { match stmt {
            Stmt::Var(var) => if let Pattern::Ident(ident) = &var.pat {
                self.locals.insert(ident.sym.clone());
            },
            Stmt::Block(b) => self.extract_locals_simple(b),
            _ => {}
        } }
    }

    fn extract_local_vars(&mut self, block: &BlockStmt) {
        for stmt in &block.body { match stmt {
            Stmt::Var(var) => if let Pattern::Ident(ident) = &var.pat {
                let mut ty_str = if let Some(t) = &var.ty { self.map_type(t) } else { "i32".to_string() };
                if ident.sym == "st" { ty_str = "SharedTensor".to_string(); }
                if ident.sym == "msg" { ty_str = "Message".to_string(); }
                if ident.sym == "pid" || ident.sym == "handle" || ident.sym == "worker" || ident.sym.contains("pid") { 
                    ty_str = "PID".to_string(); 
                }
                if ident.sym == "shape" { ty_str = "[2]usize".to_string(); }
                if ident.sym.contains("dir") || ident.sym.contains("file") || ident.sym.contains("path") || ident.sym.contains("content") || ident.sym == "s" || ident.sym == "fmt" {
                    ty_str = "[]const u8".to_string();
                }
                
                if ty_str == "PID" { 
                    self.writeln(&format!("{}: PID = PID{{ .node_id = 0, .local_id = 0 }},", ident.sym)); 
                } else { 
                    self.writeln(&format!("{}: {},", ident.sym, ty_str)); 
                }
            },
            Stmt::Block(b) => self.extract_local_vars(b),
            _ => {}
        } }
    }

    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::I32 => "i32".to_string(), Type::U32 => "u32".to_string(), Type::Bool => "bool".to_string(), Type::String => "[]const u8".to_string(), Type::PID => "PID".to_string(), Type::Void => "void".to_string(), Type::Any => "Message".to_string(), 
            Type::Array(inner) => format!("[]const {}", self.map_type(inner)),
            Type::Ref(ident) => {
                if ident.sym == "SharedTensor" { "SharedTensor".to_string() } 
                else { format!("*{}", ident.sym) }
            },
            _ => "i32".to_string(),
        }
    }

    fn indent(&mut self) { self.indent_level += 1; }
    fn dedent(&mut self) { self.indent_level -= 1; }
    fn writeln(&mut self, s: &str) { for _ in 0..self.indent_level { self.output.push_str("    "); } self.output.push_str(s); self.output.push('\n'); }
    fn write_to_case(&mut self, s: &str) { let indent = "    ".repeat(self.indent_level + 1); self.current_case_content.push_str(&format!("{}{}\n", indent, s)); }
}
