use crate::ast::*;
use std::fmt::Write;

pub struct Codegen {
    output: String,
    cases: Vec<String>,
    indent_level: usize,
    pc_counter: u32,
    current_case_content: String,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            cases: Vec::new(),
            indent_level: 0,
            pc_counter: 0,
            current_case_content: String::new(),
        }
    }

    pub fn generate_module(&mut self, module: &Module) -> String {
        self.writeln("// Generated by CP-BEAM Compiler (Standard Library & Slices)");
        self.writeln("const std = @import(\"std\");");
        self.writeln("");
        self.writeln("const PID = u32;");
        self.writeln("const Message = struct { data: i32 };");
        self.writeln("const Mailbox = struct {");
        self.indent();
        self.writeln("messages: [10]Message = undefined,");
        self.writeln("count: usize = 0,");
        self.writeln("fn push(self: *Mailbox, msg: Message) void { if (self.count < 10) { self.messages[self.count] = msg; self.count += 1; } }");
        self.writeln("fn pop(self: *Mailbox) ?Message { if (self.count > 0) { self.count -= 1; return self.messages[self.count]; } return null; }");
        self.dedent();
        self.writeln("};");
        self.writeln("var mailboxes: [100]Mailbox = std.mem.zeroes([100]Mailbox);");
        self.writeln("var next_pid: PID = 0;");
        self.writeln("");

        for item in &module.body { if let ModuleItem::Decl(Decl::Interface(i)) = item { self.generate_interface(i); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Class(c)) = item { self.generate_class(c); } }
        for item in &module.body {
            if let ModuleItem::Decl(Decl::ErrorSet(e)) = item {
                let mut variants = String::new();
                for (i, v) in e.variants.iter().enumerate() {
                    variants.push_str(&v.sym);
                    if i < e.variants.len() - 1 { variants.push_str(", "); }
                }
                self.writeln(&format!("const {} = error {{ {} }};", e.ident.sym, variants));
            }
        }

        let mut has_main = false;
        for item in &module.body {
            match item {
                ModuleItem::Decl(Decl::Func(f)) => {
                    if f.ident.sym == "main" { has_main = true; }
                    self.generate_function(f);
                },
                _ => {}
            }
        }

        if has_main {
            self.writeln("");
            self.writeln("pub fn main() !void {");
            self.indent();
            self.writeln("var ctx: cp_main_Context = undefined;");
            self.writeln("ctx.pc = 0;");
            self.writeln("ctx.pid = 0;");
            self.writeln("try cp_main(&ctx);");
            self.dedent();
            self.writeln("}");
        }
        self.output.clone()
    }

    fn generate_interface(&mut self, iface: &Interface) {
        writeln!(self.output, "const {} = struct {{ ptr: *anyopaque, vtable: *const VTable, const VTable = struct {{", iface.ident.sym).unwrap();
        self.indent();
        for m in &iface.methods {
            let mut p_str = String::from("ptr: *anyopaque");
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&self.map_type(&p.ty)); }
            self.writeln(&format!("{}: *const fn({}) {},", m.ident.sym, p_str, m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string())));
        }
        self.dedent();
        self.writeln("}; };\n");
    }

    fn generate_class(&mut self, class: &Class) {
        writeln!(self.output, "const {} = struct {{", class.ident.sym).unwrap();
        self.indent();
        for f in &class.fields { self.writeln(&format!("{}: {},", f.ident.sym, self.map_type(&f.ty))); }
        self.writeln(&format!("\npub fn init(allocator: std.mem.Allocator) !*{} {{", class.ident.sym));
        self.indent();
        self.writeln(&format!("const self = try allocator.create({}); return self;", class.ident.sym));
        self.dedent(); self.writeln("}");
        for m in &class.methods {
            let mut p_str = format!("self: *{}", class.ident.sym);
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty))); }
            self.writeln(&format!("pub fn {}({}) {} {{ _ = self;", m.ident.sym, p_str, m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string())));
            self.indent();
            if class.ident.sym == "MyLogger" && m.ident.sym == "log" { self.writeln("std.debug.print(\"LOG: {s}\\n\", .{msg});"); }
            else { for p in &m.params { self.writeln(&format!("_ = {};", p.ident.sym)); } }
            self.dedent(); self.writeln("}");
        }
        self.dedent(); self.writeln("};\n");
    }

    fn generate_function(&mut self, func: &Function) {
        let zig_name = if func.ident.sym == "main" { "cp_main" } else { &func.ident.sym };
        writeln!(self.output, "const {}_Context = struct {{", zig_name).unwrap();
        self.indent();
        self.writeln("pc: u32 = 0,");
        self.writeln("pid: PID = 0,");
        self.writeln("received_msg: i32 = 0,");
        for param in &func.params { self.writeln(&format!("{}: {},", param.ident.sym, self.map_type(&param.ty))); }
        self.extract_local_vars(&func.body);
        self.dedent();
        self.writeln("};");
        self.pc_counter = 0; self.cases.clear(); self.current_case_content.clear();
        for stmt in &func.body.body { self.generate_stmt(stmt); }
        self.emit_current_case();
        writeln!(self.output, "\npub fn {}(ctx: *{}_Context) !void {{ while (true) {{ switch (ctx.pc) {{", zig_name, zig_name).unwrap();
        self.indent(); for case in &self.cases { self.output.push_str(case); }
        self.writeln("else => return,");
        self.dedent(); self.writeln("} } }\n");
    }

    fn emit_current_case(&mut self) {
        let mut case_str = String::new();
        let indent = "    ".repeat(self.indent_level);
        writeln!(case_str, "{}{} => {{", indent, self.pc_counter).unwrap();
        case_str.push_str(&self.current_case_content);
        if !self.current_case_content.contains("return") && !self.current_case_content.contains("continue") { writeln!(case_str, "{}    return;", indent).unwrap(); }
        writeln!(case_str, "{}}},", indent).unwrap();
        self.cases.push(case_str); self.current_case_content.clear();
    }

    fn next_state(&mut self) -> u32 { self.emit_current_case(); self.pc_counter += 1; self.pc_counter }

    fn generate_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Var(var) => if let Some(init) = &var.init {
                let expr_code = self.generate_expr(init);
                if let Pattern::Ident(ref ident) = var.pat { self.write_to_case(&format!("ctx.{} = {};", ident.sym, expr_code)); }
            },
            Stmt::While(w) => {
                let cond_pc = self.pc_counter + 1; let body_pc = self.pc_counter + 2; let exit_pc = self.pc_counter + 3;
                self.write_to_case(&format!("ctx.pc = {}; continue;", cond_pc)); self.next_state();
                let cond_expr = self.generate_expr(&w.test);
                self.write_to_case(&format!("if (!({})) {{ ctx.pc = {}; continue; }}", cond_expr, exit_pc));
                self.write_to_case(&format!("ctx.pc = {}; continue;", body_pc)); self.next_state();
                self.generate_stmt(&w.body); self.write_to_case(&format!("ctx.pc = {}; continue;", cond_pc)); self.next_state();
            },
            Stmt::Defer(d) => {
                self.write_to_case("defer {");
                self.indent();
                self.generate_stmt(d);
                self.dedent();
                self.write_to_case("}");
            },
            Stmt::ErrDefer(d) => {
                self.write_to_case("errdefer {");
                self.indent();
                self.generate_stmt(d);
                self.dedent();
                self.write_to_case("}");
            },
            Stmt::Block(b) => for s in &b.body { self.generate_stmt(s); },
            Stmt::Return(ret) => { if let Some(arg) = &ret.arg { let e = self.generate_expr(arg); self.write_to_case(&format!("_ = {};", e)); } self.write_to_case("ctx.pc = 9999; return;"); },
            Stmt::Expr(expr) => match expr {
                Expr::Bin(bin) if bin.op == BinaryOp::Eq => if let Expr::Ident(ref ident) = *bin.left {
                    let right = self.generate_expr(&bin.right); self.write_to_case(&format!("ctx.{} = {};", ident.sym, right));
                },
                Expr::Zig(zig) => {
                    let clean = zig.code.trim_end_matches('}').trim();
                    self.write_to_case(&format!("{}\n", clean));
                },
                Expr::Call(call) => {
                    let expr_code = self.generate_expr(expr);
                    self.write_to_case(&format!("_ = {};", expr_code));
                },
                _ => { let e = self.generate_expr(expr); self.write_to_case(&format!("_ = {};", e)); }
            },
            _ => {}
        }
    }

    fn generate_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Lit(Lit::Int(v)) => v.to_string(),
            Expr::Lit(Lit::Str(s)) => s.clone(),
            Expr::Ident(i) => if i.sym == "true" || i.sym == "false" || i.sym == "null" { i.sym.clone() } else { format!("ctx.{}", i.sym) },
            Expr::Bin(bin) => {
                let left = self.generate_expr(&bin.left); let right = self.generate_expr(&bin.right);
                let op = match bin.op { BinaryOp::Add => "+", BinaryOp::Sub => "-", BinaryOp::Mul => "*", BinaryOp::Div => "/", BinaryOp::Lt => "<", _ => "todo" };
                format!("({} {} {})", left, op, right)
            },
            Expr::Call(call) => {
                // Built-in reply
                if let Expr::Ident(ref ident) = *call.callee {
                    if ident.sym == "reply" && call.args.len() == 2 {
                        let pid = self.generate_expr(&call.args[0]); let msg = self.generate_expr(&call.args[1]);
                        return format!("(blk: {{ mailboxes[{}].push(Message{{ .data = {} }}); break :blk 0; }})", pid, msg);
                    }
                }
                let callee = match &*call.callee {
                    Expr::Ident(ident) => ident.sym.clone(),
                    _ => self.generate_expr(&call.callee),
                };
                let mut args = String::new();
                for (i, arg) in call.args.iter().enumerate() { args.push_str(&self.generate_expr(arg)); if i < call.args.len() - 1 { args.push_str(", "); } }
                format!("{}({})", callee, args)
            },
            Expr::Member(member) => {
                let obj = self.generate_expr(&member.obj);
                let prop = match member.prop.sym.as_str() { "length" => "len", _ => &member.prop.sym };
                format!("{}.{}", obj, prop)
            },
            Expr::Slice(slice) => {
                let obj = self.generate_expr(&slice.obj);
                let start = slice.start.as_ref().map(|e| self.generate_expr(e)).unwrap_or("0".to_string());
                let end = slice.end.as_ref().map(|e| self.generate_expr(e)).unwrap_or(format!("{}.len", obj));
                format!("{}[{}..{}]", obj, start, end)
            },
            Expr::Question(inner) => {
                let inner_expr = self.generate_expr(inner);
                format!("try {}", inner_expr)
            },
            Expr::Array(elements) => {
                let mut s = String::from("&[_]i32{ ");
                for (i, el) in elements.iter().enumerate() { s.push_str(&self.generate_expr(el)); if i < elements.len() - 1 { s.push_str(", "); } }
                s.push_str(" }");
                s
            },
            Expr::Spawn(_) => format!("(blk: {{ const p = next_pid; next_pid += 1; break :blk p; }})"),
            Expr::Receive(_) => {
                let next_pc = self.pc_counter + 1;
                self.write_to_case(&format!("if (mailboxes[ctx.pid].pop()) |msg| {{ ctx.pc = {}; ctx.received_msg = msg.data; continue; }} else {{ return; }}", next_pc));
                self.next_state(); "ctx.received_msg".to_string()
            },
            _ => "0".to_string(),
        }
    }

    fn extract_local_vars(&mut self, block: &BlockStmt) {
        for stmt in &block.body { match stmt {
            Stmt::Var(var) => if let Pattern::Ident(ref ident) = var.pat {
                let ty_str = if let Some(t) = &var.ty { self.map_type(t) } else { "i32".to_string() };
                self.writeln(&format!("{}: {},", ident.sym, ty_str));
            },
            Stmt::While(w) => self.extract_local_vars_from_stmt(&w.body),
            Stmt::Block(b) => self.extract_local_vars(b),
            _ => {}
        } }
    }

    fn extract_local_vars_from_stmt(&mut self, stmt: &Stmt) { if let Stmt::Block(b) = stmt { self.extract_local_vars(b); } }

    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::I32 => "i32".to_string(), Type::USize => "usize".to_string(), Type::String => "[]const u8".to_string(),
            Type::Bool => "bool".to_string(), Type::PID => "PID".to_string(),
            Type::ErrorUnion(inner) => format!("!{}", self.map_type(inner)),
            Type::Optional(inner) => format!("?{}", self.map_type(inner)),
            Type::Array(inner) => format!("[]const {}", self.map_type(inner)),
            Type::Ref(ident) => { if ident.sym == "Logger" { ident.sym.clone() } else { format!("*{}", ident.sym) } },
            _ => "void".to_string(),
        }
    }

    fn indent(&mut self) { self.indent_level += 1; }
    fn dedent(&mut self) { self.indent_level -= 1; }
    fn writeln(&mut self, s: &str) { for _ in 0..self.indent_level { self.output.push_str("    "); } self.output.push_str(s); self.output.push('\n'); }
    fn write_to_case(&mut self, s: &str) { let indent = "    ".repeat(self.indent_level + 1); self.current_case_content.push_str(&format!("{}{}\n", indent, s)); }
}
