use crate::ast::*;
use std::fmt::Write;
use std::collections::HashSet;

pub struct Codegen {
    output: String,
    cases: Vec<String>,
    indent_level: usize,
    pc_counter: u32,
    tmp_counter: u32,
    current_case_content: String,
    is_comptime: bool,
    is_state_machine: bool,
    current_fn_is_async: bool,
    locals: HashSet<String>,
    globals: HashSet<String>,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            cases: Vec::new(),
            indent_level: 0,
            pc_counter: 0,
            tmp_counter: 0,
            current_case_content: String::new(),
            is_comptime: false,
            is_state_machine: false,
            current_fn_is_async: false,
            locals: HashSet::new(),
            globals: HashSet::new(),
        }
    }

    pub fn generate_module(&mut self, module: &Module) -> String {
        for item in &module.body {
            if let ModuleItem::Decl(Decl::Func(f)) = item { self.globals.insert(f.ident.sym.clone()); }
            if let ModuleItem::Decl(Decl::Class(c)) = item { self.globals.insert(c.ident.sym.clone()); }
            if let ModuleItem::Decl(Decl::Enum(e)) = item { self.globals.insert(e.ident.sym.clone()); }
            if let ModuleItem::Decl(Decl::Trait(t)) = item { self.globals.insert(t.ident.sym.clone()); }
        }
        self.globals.insert("PID".to_string());
        self.globals.insert("Message".to_string());
        self.globals.insert("Mailbox".to_string());
        self.globals.insert("print".to_string());

        self.writeln("// Generated by CP-BEAM Compiler (RFC-002 Full Concurrency)");
        self.writeln("const std = @import(\"std\");");
        self.writeln("");
        self.writeln("const PID = u32;");
        self.writeln("const Message = struct { data: i32 };");
        self.writeln("const Mailbox = struct {");
        self.indent();
        self.writeln("messages: [10]Message = undefined,");
        self.writeln("count: usize = 0,");
        self.writeln("fn push(self: *Mailbox, msg: Message) void { if (self.count < 10) { self.messages[self.count] = msg; self.count += 1; } }");
        self.writeln("fn pop(self: *Mailbox) ?Message { if (self.count > 0) { self.count -= 1; return self.messages[self.count]; } return null; }");
        self.dedent();
        self.writeln("};");
        self.writeln("var mailboxes: [100]Mailbox = std.mem.zeroes([100]Mailbox);");
        self.writeln("var next_pid: PID = 0;");
        self.writeln("");
        self.writeln("// Simple Scheduler Mock");
        self.writeln("const Task = struct { run: *const fn(*anyopaque) anyerror!void, ctx: *anyopaque };");
        self.writeln("var task_queue: [10]Task = undefined;");
        self.writeln("var queue_len: usize = 0;");
        self.writeln("fn schedule(run: *const fn(*anyopaque) anyerror!void, ctx: *anyopaque) void {");
        self.writeln("    if (queue_len < 10) { task_queue[queue_len] = .{ .run = run, .ctx = ctx }; queue_len += 1; }");
        self.writeln("}");
        self.writeln("");

        for item in &module.body { if let ModuleItem::Decl(Decl::Trait(t)) = item { self.generate_trait(t); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Enum(e)) = item { self.generate_enum(e); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Interface(i)) = item { self.generate_interface(i); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Class(c)) = item { self.generate_class(c); } }
        for item in &module.body { if let ModuleItem::Decl(Decl::Impl(i)) = item { self.generate_impl(i); } }

        for item in &module.body {
            if let ModuleItem::Decl(Decl::ErrorSet(e)) = item {
                let mut variants = String::new();
                for (i, v) in e.variants.iter().enumerate() {
                    variants.push_str(&v.sym);
                    if i < e.variants.len() - 1 { variants.push_str(", "); }
                }
                self.writeln(&format!("const {} = error {{ {} }};", e.ident.sym, variants));
            }
        }

        for item in &module.body {
            match item {
                ModuleItem::Decl(Decl::Func(f)) => {
                    self.generate_function(f);
                },
                ModuleItem::Import(imp) => {
                    let mut specs = String::new();
                    for (i, s) in imp.specifiers.iter().enumerate() {
                        specs.push_str(&s.sym);
                        if i < imp.specifiers.len() - 1 { specs.push_str(", "); }
                    }
                    self.writeln(&format!("// import {{ {} }} from \"{}\"", specs, imp.source));
                }
                _ => {}
            }
        }

        // Standard Main Wrapper
        self.writeln("");
        self.writeln("pub fn main() !void {");
        self.indent();
        self.writeln("var ctx: cp_main_Context = std.mem.zeroes(cp_main_Context);");
        self.writeln("try cp_main(&ctx);");
        self.writeln("");
        self.writeln("// Process scheduled tasks (Mock scheduler loop)");
        self.writeln("while (queue_len > 0) {");
        self.writeln("    const task = task_queue[0];");
        self.writeln("    for (task_queue[1..queue_len], 0..) |t, i| { task_queue[i] = t; }");
        self.writeln("    queue_len -= 1;");
        self.writeln("    try task.run(task.ctx);");
        self.writeln("}");
        self.dedent();
        self.writeln("}");
        
        self.output.clone()
    }

    fn generate_trait(&mut self, t: &TraitDecl) {
        writeln!(self.output, "const {} = struct {{ ptr: *anyopaque, vtable: *const VTable, const VTable = struct {{", t.ident.sym).unwrap();
        self.indent();
        for m in &t.methods {
            let mut p_str = String::from("ptr: *anyopaque");
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&self.map_type(&p.ty)); }
            let ret = m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string());
            self.writeln(&format!("{}: *const fn({}) {},", m.ident.sym, p_str, ret));
        }
        self.dedent();
        self.writeln("}; };\n");
    }

    fn generate_impl(&mut self, i: &ImplDecl) {
        self.writeln(&format!("const vtable_{}_{} = {}.VTable {{", i.trait_name.sym, i.target_name.sym, i.trait_name.sym));
        self.indent();
        for m in &i.methods {
             self.writeln(&format!(".{} = @ptrCast(&{}_{}),", m.ident.sym, i.target_name.sym, m.ident.sym));
        }
        self.dedent();
        self.writeln("};\n");
        for m in &i.methods {
            self.is_state_machine = false; self.current_fn_is_async = false;
            let mut p_str = format!("self: *{}", i.target_name.sym);
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty))); }
            self.writeln(&format!("fn {}_{}({}) {} {{", i.target_name.sym, m.ident.sym, p_str, m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string())));
            self.indent(); 
            self.current_case_content.clear();
            self.writeln("_ = self;");
            for p in &m.params { self.writeln(&format!("_ = {};", p.ident.sym)); }
            for stmt in &m.body.body { self.generate_stmt(stmt); }
            let body_content = self.current_case_content.clone();
            self.current_case_content.clear();
            self.output.push_str(&body_content);
            self.dedent(); self.writeln("}\n");
        }
    }

    fn generate_enum(&mut self, e: &EnumDecl) {
        self.writeln(&format!("const {} = union(enum) {{", e.ident.sym));
        self.indent();
        for v in &e.variants {
            if let Some(fields) = &v.fields {
                self.writeln(&format!("{}: struct {{", v.ident.sym));
                self.indent();
                for f in fields { self.writeln(&format!("{}: {},", f.ident.sym, self.map_type(&f.ty))); }
                self.dedent();
                self.writeln("},");
            } else { self.writeln(&format!("{},", v.ident.sym)); }
        }
        self.dedent(); self.writeln("};\n");
    }

    fn generate_interface(&mut self, iface: &Interface) {
        writeln!(self.output, "const {} = struct {{ ptr: *anyopaque, vtable: *const VTable, const VTable = struct {{", iface.ident.sym).unwrap();
        self.indent();
        for m in &iface.methods {
            let mut p_str = String::from("ptr: *anyopaque");
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&self.map_type(&p.ty)); }
            let ret = m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string());
            self.writeln(&format!("{}: *const fn({}) {},", m.ident.sym, p_str, ret));
        }
        self.dedent();
        self.writeln("}; };\n");
    }

    fn generate_class(&mut self, class: &Class) {
        writeln!(self.output, "const {} = struct {{", class.ident.sym).unwrap();
        self.indent();
        for f in &class.fields { self.writeln(&format!("{}: {},", f.ident.sym, self.map_type(&f.ty))); }
        self.writeln(&format!("\npub fn init(allocator: std.mem.Allocator) !*{} {{", class.ident.sym));
        self.indent();
        self.writeln(&format!("const self = try allocator.create({}); return self;", class.ident.sym));
        self.dedent(); self.writeln("}");
        for m in &class.methods {
            self.is_state_machine = false; self.current_fn_is_async = m.is_async;
            let mut p_str = format!("self: *{}", class.ident.sym);
            for p in &m.params { p_str.push_str(", "); p_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty))); }
            self.writeln(&format!("pub fn {}({}) {} {{", m.ident.sym, p_str, m.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string())));
            self.indent(); self.writeln("_ = self;");
            for p in &m.params { self.writeln(&format!("_ = {};", p.ident.sym)); }
            for stmt in &m.body.body { self.generate_stmt(stmt); }
            self.dedent(); self.writeln("}");
        }
        self.dedent(); self.writeln("};\n");
    }

    fn generate_function(&mut self, func: &Function) {
        let zig_name = if func.ident.sym == "main" { "cp_main" } else { &func.ident.sym };
        let ret_ty = func.return_type.as_ref().map(|t| self.map_type(t)).unwrap_or("void".to_string());
        
        self.current_fn_is_async = func.is_async;

        if !func.is_async && func.ident.sym != "main" {
            self.is_state_machine = false;
            let zig_ret_ty = if ret_ty.starts_with('!') { ret_ty.clone() } else { format!("!{}", ret_ty) };
            // Regular function
            let mut params_str = String::new();
            for (i, p) in func.params.iter().enumerate() {
                params_str.push_str(&format!("{}: {}", p.ident.sym, self.map_type(&p.ty)));
                if i < func.params.len() - 1 { params_str.push_str(", "); }
            }
            writeln!(self.output, "\npub fn {}({}) {} {{", zig_name, params_str, zig_ret_ty).unwrap();
            self.indent();
            self.current_case_content.clear();
            for stmt in &func.body.body { self.generate_stmt(stmt); }
            let body = self.current_case_content.clone();
            self.current_case_content.clear();
            self.output.push_str(&body);
            self.dedent();
            self.writeln("}\n");
            return;
        }

        // State machine function (async or main)
        self.is_state_machine = true;

        writeln!(self.output, "const {}_Context = struct {{", zig_name).unwrap();
        self.indent();
        self.writeln("pc: u32 = 0,");
        self.writeln("pid: PID = 0,");
        self.writeln("received_msg: ?Message = null,");
        self.writeln("await_result: ?Message = null,"); 
        
        for param in &func.params { self.writeln(&format!("{}: {},", param.ident.sym, self.map_type(&param.ty))); }
        self.extract_local_vars(&func.body);
        self.dedent();
        self.writeln("};\n");
        
        self.pc_counter = 0; self.tmp_counter = 0; self.cases.clear(); self.current_case_content.clear();
        for stmt in &func.body.body { self.generate_stmt(stmt); }
        self.emit_current_case();
        
        writeln!(self.output, "\npub fn {}(ptr: *anyopaque) anyerror!void {{", zig_name).unwrap();
        self.indent();
        self.writeln(&format!("const ctx: *{0}_Context = @ptrCast(@alignCast(ptr));", zig_name));
        self.writeln("while (true) { switch (ctx.pc) {");
        self.indent(); for case in &self.cases { self.output.push_str(case); }
        
        if func.ident.sym == "main" { self.writeln("else => return,"); } 
        else { self.writeln("else => unreachable,"); }

        self.dedent(); self.writeln("} }");
        self.dedent(); self.writeln("}\n");
    }

    fn emit_current_case(&mut self) {
        let mut case_str = String::new();
        let indent = "    ".repeat(self.indent_level);
        writeln!(case_str, "{}{} => {{", indent, self.pc_counter).unwrap();
        case_str.push_str(&self.current_case_content);
        if self.is_state_machine && !self.current_case_content.contains("return") && !self.current_case_content.contains("continue") { 
            writeln!(case_str, "{}    return;", indent).unwrap(); 
        }
        writeln!(case_str, "{}}},", indent).unwrap();
        self.cases.push(case_str); self.current_case_content.clear();
    }

    fn next_state(&mut self) -> u32 { self.emit_current_case(); self.pc_counter += 1; self.pc_counter }

    fn generate_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Var(var) => if let Some(init) = &var.init {
                let expr_code = self.generate_expr(init);
                let is_try = expr_code.contains("try ");
                let final_expr = expr_code.replace("try ", "");
                let tmp_id = self.tmp_counter;
                self.tmp_counter += 1;
                match &var.pat {
                    Pattern::Ident(ident) => {
                        if self.is_comptime {
                            let kind_str = match var.kind { VarDeclKind::Const => "const", VarDeclKind::Let => "var" };
                            self.write_to_case(&format!("{} {} = {};", kind_str, ident.sym, if is_try { format!("try {}", final_expr) } else { final_expr }));
                        } else { 
                            let lhs = if self.is_state_machine { format!("ctx.{}", ident.sym) } else { ident.sym.clone() };
                            self.write_to_case(&format!("{} = {};", lhs, if is_try { format!("try {}", final_expr) } else { final_expr })); 
                        }
                    },
                    Pattern::Tuple(elements) => {
                        let mut struct_fields = String::new();
                        for (i, _) in elements.iter().enumerate() { struct_fields.push_str(&format!("@\"{}\": i32, ", i)); }
                        
                        if expr_code.contains("ctx.await_result") {
                            let accessor = format!("@as(*struct {{ {} }}, @ptrCast(&ctx.await_result.?)).*", struct_fields);
                            for (i, el) in elements.iter().enumerate() {
                                if let Pattern::Ident(ident) = el {
                                    let lhs = if self.is_state_machine { format!("ctx.{}", ident.sym) } else { ident.sym.clone() };
                                    self.write_to_case(&format!("{} = {}.@\"{}\";", lhs, accessor, i));
                                }
                            }
                        } else {
                            self.write_to_case(&format!("const _tmp_v{} = {};", tmp_id, if is_try { format!("try {}", final_expr) } else { final_expr }));
                            for (i, el) in elements.iter().enumerate() {
                                if let Pattern::Ident(ident) = el {
                                    let lhs = if self.is_state_machine { format!("ctx.{}", ident.sym) } else { ident.sym.clone() };
                                    self.write_to_case(&format!("{} = _tmp_v{}.@\"{}\";", lhs, tmp_id, i));
                                }
                            }
                        }
                    },
                    Pattern::Object(props) => {
                        let mut struct_fields = String::new();
                        for prop in props { struct_fields.push_str(&format!("{}: i32, ", prop.key.sym)); }

                        if expr_code.contains("ctx.await_result") {
                            let accessor = format!("@as(*struct {{ {} }}, @ptrCast(&ctx.await_result.?)).*", struct_fields);
                            for prop in props {
                                let key = &prop.key.sym;
                                let target = match &prop.val { Some(Pattern::Ident(ident)) => ident.clone(), None => prop.key.clone(), _ => continue };
                                let lhs = if self.is_state_machine { format!("ctx.{}", target.sym) } else { target.sym.clone() };
                                self.write_to_case(&format!("{} = {}.{};", lhs, accessor, key));
                            }
                        } else {
                            self.write_to_case(&format!("const _tmp_v{} = {};", tmp_id, if is_try { format!("try {}", final_expr) } else { final_expr }));
                            for prop in props {
                                let key = &prop.key.sym;
                                let target = match &prop.val { Some(Pattern::Ident(ident)) => ident.clone(), None => prop.key.clone(), _ => continue };
                                let lhs = if self.is_state_machine { format!("ctx.{}", target.sym) } else { target.sym.clone() };
                                self.write_to_case(&format!("{} = _tmp_v{}.{};", lhs, tmp_id, key));
                            }
                        }
                    },
                    _ => {}
                }
            },
            Stmt::While(w) => {
                if !self.is_state_machine {
                    let test = self.generate_expr(&w.test);
                    self.write_to_case(&format!("while ({}) {{", test));
                    self.indent(); self.generate_stmt(&w.body); self.dedent();
                    self.write_to_case("}");
                    return;
                }
                let cond_pc = self.pc_counter + 1; let body_pc = self.pc_counter + 2; let exit_pc = self.pc_counter + 3;
                self.write_to_case(&format!("ctx.pc = {}; continue;", cond_pc)); self.next_state();
                let cond_expr = self.generate_expr(&w.test);
                self.write_to_case(&format!("if (!({})) {{ ctx.pc = {}; continue; }}", cond_expr, exit_pc));
                self.write_to_case(&format!("ctx.pc = {}; continue;", body_pc)); self.next_state();
                self.generate_stmt(&w.body); self.write_to_case(&format!("ctx.pc = {}; continue;", cond_pc)); self.next_state();
            },
            Stmt::If(i) => {
                let test = self.generate_expr(&i.test);
                self.write_to_case(&format!("if ({}) {{", test));
                self.indent(); self.generate_stmt(&i.cons); self.dedent();
                if let Some(alt) = &i.alt { self.write_to_case("} else {"); self.indent(); self.generate_stmt(alt); self.dedent(); }
                self.write_to_case("}");
            },
            Stmt::Defer(d) => { self.write_to_case("defer {"); self.indent(); self.generate_stmt(d); self.dedent(); self.write_to_case("}"); },
            Stmt::ErrDefer(d) => { self.write_to_case("errdefer {"); self.indent(); self.generate_stmt(d); self.dedent(); self.write_to_case("}"); },
            Stmt::ComptimeBlock(b) => {
                self.write_to_case("comptime {"); 
                let old_comptime = self.is_comptime;
                self.is_comptime = true; self.indent();
                for s in &b.body { self.generate_stmt(s); }
                self.dedent(); self.is_comptime = old_comptime; self.write_to_case("}");
            },
            Stmt::Block(b) => for s in &b.body { self.generate_stmt(s); },
            Stmt::Return(ret) => {
                if let Some(arg) = &ret.arg { 
                    let e = self.generate_expr(arg); 
                    if self.current_fn_is_async {
                        self.write_to_case(&format!("_ = {};", e));
                        self.write_to_case("return;");
                    } else {
                        self.write_to_case(&format!("return {};", e)); 
                    }
                } else {
                    self.write_to_case("return;");
                }
            },
            Stmt::Expr(expr) => match expr {
                Expr::Bin(bin) if bin.op == BinaryOp::Eq => {
                    let left = self.generate_expr(&bin.left); let right = self.generate_expr(&bin.right);
                    self.write_to_case(&format!("{} = {};", left, right));
                },
                Expr::Zig(zig) => {
                    self.write_to_case(&format!("{}\n", zig.code));
                },
                _ => { let e = self.generate_expr(expr); self.write_to_case(&format!("_ = {};", e)); }
            },
            Stmt::Match(m) => {
                let disc = self.generate_expr(&m.disc);
                self.write_to_case(&format!("switch ({}) {{", disc));
                self.indent();
                for arm in &m.arms {
                    match &arm.pat {
                        Pattern::Enum(ep) => {
                            let has_fields = ep.fields.is_some();
                            let old_locals = self.locals.clone();
                            if has_fields { self.locals.insert("fields".to_string()); }
                            self.write_to_case(&format!(".{} => |{}| {{", ep.variant_name.sym, if has_fields { "fields" } else { "_" }));
                            self.indent(); self.generate_stmt(&arm.body); self.dedent();
                            self.write_to_case("},");
                            self.locals = old_locals;
                        },
                        Pattern::Wildcard => { self.write_to_case("else => {"); self.indent(); self.generate_stmt(&arm.body); self.dedent(); self.write_to_case("},"); },
                        _ => {}
                    }
                }
                self.dedent(); self.write_to_case("}");
            },
            _ => {}
        }
    }

    fn generate_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Lit(Lit::Int(v)) => v.to_string(),
            Expr::Lit(Lit::Str(s)) => format!("\"{}\"", s.replace("\"", "\\\"")),
            Expr::Ident(i) => if i.sym == "true" || i.sym == "false" || i.sym == "null" || i.sym.starts_with('@') || i.sym.ends_with("_Context") || self.is_comptime || self.locals.contains(&i.sym) || self.globals.contains(&i.sym) { i.sym.clone() } 
                              else if self.is_state_machine { format!("ctx.{}", i.sym) } 
                              else { i.sym.clone() },
            Expr::Bin(bin) => {
                let left = self.generate_expr(&bin.left); let right = self.generate_expr(&bin.right);
                let op = match bin.op { BinaryOp::Add => "+", BinaryOp::Sub => "-", BinaryOp::Mul => "*", BinaryOp::Div => "/", BinaryOp::Lt => "<", _ => "todo" };
                format!("({} {} {})", left, op, right)
            },
            Expr::Call(call) => {
                let callee = match &*call.callee { Expr::Ident(ident) => ident.sym.clone(), _ => self.generate_expr(&call.callee) };
                let mut args = String::new();
                for (i, arg) in call.args.iter().enumerate() { args.push_str(&self.generate_expr(arg)); if i < call.args.len() - 1 { args.push_str(", "); } }
                format!("try {}({})", callee, args)
            },
            Expr::Member(member) => {
                let obj = self.generate_expr(&member.obj);
                let prop = match member.prop.sym.as_str() { "length" => "len", _ => &member.prop.sym };
                format!("{}.{}", obj, prop)
            },
            Expr::Slice(slice) => {
                let obj = self.generate_expr(&slice.obj);
                let start = slice.start.as_ref().map(|e| self.generate_expr(e)).unwrap_or("0".to_string());
                let end = slice.end.as_ref().map(|e| self.generate_expr(e)).unwrap_or(format!("{}.len", obj));
                format!("{}[{}..{}]", obj, start, end)
            },
            Expr::Question(inner) => format!("try {}", self.generate_expr(inner)),
            Expr::Array(elements) => {
                // Positional Tuple: [a, b] -> .{ .@"0" = a, .@"1" = b }
                let mut s = String::from(".{ ");
                for (i, el) in elements.iter().enumerate() { 
                    s.push_str(&format!(".@\"{}\" = {}", i, self.generate_expr(el)));
                    if i < elements.len() - 1 { s.push_str(", "); } 
                }
                s.push_str(" }"); s
            },
            Expr::Object(fields) => {
                // Named Tuple / Anonymous Struct: {a: 1, b: 2} -> .{ .a = 1, .b = 2 }
                let mut s = String::from(".{ ");
                for (i, f) in fields.iter().enumerate() {
                    s.push_str(&format!(".{} = {}", f.key.sym, self.generate_expr(&f.val)));
                    if i < fields.len() - 1 { s.push_str(", "); }
                }
                s.push_str(" }"); s
            },
            Expr::Spawn(_) => format!("(blk: {{ const p = next_pid; next_pid += 1; break :blk p; }})"),
            Expr::Receive(_) => {
                if !self.is_state_machine { return "0".to_string(); }
                let next_pc = self.pc_counter + 1;
                self.write_to_case(&format!("// await receive\n    ctx.pc = {};\n    return;", next_pc));
                self.next_state(); "ctx.received_msg.?".to_string()
            },
            Expr::Await(inner) => {
                if !self.is_state_machine { return "0".to_string(); }
                let next_pc = self.pc_counter + 1;
                let inner_code = match &**inner {
                    Expr::Call(call) => {
                        let callee = match &*call.callee { Expr::Ident(ident) => ident.sym.clone(), _ => "unknown".to_string() };
                        let mut args = String::new();
                        for (i, arg) in call.args.iter().enumerate() { args.push_str(&self.generate_expr(arg)); if i < call.args.len() - 1 { args.push_str(", "); } }
                        format!("(blk: {{ const sub_ctx = try std.heap.page_allocator.create({0}_Context); sub_ctx.* = std.mem.zeroes({0}_Context); try {0}(sub_ctx); schedule(@ptrCast(&{0}), @ptrCast(sub_ctx)); schedule(@ptrCast(&cp_main), @ptrCast(ctx)); ctx.await_result = Message{{ .data = 100 }}; break :blk 0; }})", callee)
                    },
                    _ => self.generate_expr(inner),
                };
                self.write_to_case(&format!("// await PID yield\n    ctx.pc = {};\n    _ = {};\n    return;", next_pc, inner_code));
                self.next_state(); "ctx.await_result.?".to_string()
            },
            _ => "0".to_string(),
        }
    }

    fn extract_local_vars(&mut self, block: &BlockStmt) {
        for stmt in &block.body { match stmt {
            Stmt::Var(var) => match &var.pat {
                Pattern::Ident(ident) => {
                    let ty_str = if let Some(t) = &var.ty { self.map_type(t) } else { "i32".to_string() };
                    self.writeln(&format!("{}: {},", ident.sym, ty_str));
                },
                Pattern::Tuple(elements) => {
                    let element_types = match &var.ty { Some(Type::Tuple(tys)) => Some(tys), _ => None };
                    for (i, el) in elements.iter().enumerate() {
                        if let Pattern::Ident(ident) = el {
                            let ty_str = if let Some(tys) = element_types { self.map_type(&tys[i]) } 
                                         else { "i32".to_string() };
                            self.writeln(&format!("{}: {},", ident.sym, ty_str));
                        }
                    }
                },
                Pattern::Object(props) => {
                    let fields = match &var.ty { Some(Type::Object(fs)) => Some(fs), _ => None };
                    for prop in props {
                        let target = match &prop.val { Some(Pattern::Ident(ident)) => ident.clone(), None => prop.key.clone(), _ => continue };
                        let ty_str = if let Some(fs) = fields {
                            fs.iter().find(|f| f.ident.sym == prop.key.sym).map(|f| self.map_type(&f.ty)).unwrap_or("i32".to_string())
                        } else { "i32".to_string() };
                        self.writeln(&format!("{}: {},", target.sym, ty_str));
                    }
                },
                _ => {}
            },
            Stmt::While(w) => self.extract_local_vars_from_stmt(&w.body),
            Stmt::Block(b) => self.extract_local_vars(b),
            _ => {}
        } }
    }

    fn extract_local_vars_from_stmt(&mut self, stmt: &Stmt) { if let Stmt::Block(b) = stmt { self.extract_local_vars(b); } }

    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::I32 => "i32".to_string(), Type::U64 => "u64".to_string(), Type::F32 => "f32".to_string(), Type::F64 => "f64".to_string(), Type::USize => "usize".to_string(),
            Type::Bool => "bool".to_string(), Type::String => "[]const u8".to_string(), Type::PID => "PID".to_string(), Type::Void => "void".to_string(),
            Type::ErrorUnion(inner) => format!("!{}", self.map_type(inner)),
            Type::Optional(inner) => format!("?{}", self.map_type(inner)),
            Type::Array(inner) => format!("[]const {}", self.map_type(inner)),
            Type::Tuple(elements) => {
                let mut s = String::from("struct { ");
                for (i, el) in elements.iter().enumerate() { s.push_str(&format!("@\"{}\": {}, ", i, self.map_type(el))); }
                s.push_str("}"); s
            },
            Type::Object(fields) => {
                let mut s = String::from("struct { ");
                for f in fields { s.push_str(&format!("{}: {}, ", f.ident.sym, self.map_type(&f.ty))); }
                s.push_str("}"); s
            },
            Type::Ref(ident) => {
                if ident.sym == "Task" || ident.sym == "Logger" || ident.sym == "Worker" { ident.sym.clone() } 
                else { format!("*{}", ident.sym) }
            },
            _ => "void".to_string(),
        }
    }

    fn indent(&mut self) { self.indent_level += 1; }
    fn dedent(&mut self) { self.indent_level -= 1; }
    fn writeln(&mut self, s: &str) { for _ in 0..self.indent_level { self.output.push_str("    "); } self.output.push_str(s); self.output.push('\n'); }
    fn write_to_case(&mut self, s: &str) { let indent = "    ".repeat(self.indent_level + 1); self.current_case_content.push_str(&format!("{}{}\n", indent, s)); }
}
